# Generated by Django 5.2.8 on 2025-11-30 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('reserved', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='The scanned ticket token', max_length=128)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('reason', models.CharField(blank=True, help_text='redeemed', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('holder_email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('barcode_data', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_quantity', models.PositiveIntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('order_placeholder', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('per_ticket_capacity', models.PositiveIntegerField(default=1, help_text='Ticket can carry multiple users')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['start_at'], name='tickets_eve_start_a_6e6ea4_idx'), models.Index(fields=['is_published'], name='tickets_eve_is_publ_27db9a_idx')],
            },
        ),
    ]
