# Generated by Django 5.2.8 on 2025-12-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_at'], 'permissions': [('manage_event', 'Can manage event and ticket types'), ('view_event_reports', 'Can view event sales and attendance reports'), ('scan_tickets', 'Can scan tickets at event entry')]},
        ),
    ]
