# Generated by Django 5.2.8 on 2025-12-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_eventimage_event_cover_event_meta_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_at']},
        ),
    ]
