# Generated by Django 5.2.8 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_at'], 'permissions': [('manage_event', 'Can manage event and ticket types'), ('view_event_reports', 'Can view event sales and attendance reports'), ('scan_tickets', 'Can scan tickets at event entry')]},
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of tickets of this type available for sale', null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='id',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_event_ticket_type_name'),
        ),
    ]
