# Generated by Django 5.2.8 on 2025-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_event_options_alter_tickettype_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickettype',
            name='unique_event_ticket_type_name',
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name', 'id'), name='unique_event_ticket_type_name'),
        ),
    ]
