# Generated by Django 5.2.8 on 2025-12-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_tickettype_unique_event_ticket_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='position',
        ),
    ]
