# Generated by Django 5.2.8 on 2025-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
