# Generated by Django 5.2.8 on 2025-12-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_ticket_order_remove_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent_mail',
            field=models.BooleanField(default=False),
        ),
    ]
