# Generated by Django 5.2.8 on 2025-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_sent_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
