# Generated by Django 5.2.8 on 2025-11-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tenants', '0002_alter_client_schema_name_alter_domain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.client'),
        ),
    ]
