# Generated by Django 5.2.8 on 2025-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLaunchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('concert', 'Concert / Festival'), ('conference', 'Conference / Expo'), ('training', 'Training / Workshop'), ('church', 'Church / Charity Event'), ('sports', 'Sports / Tournament'), ('other', 'Other')], max_length=50)),
                ('event_details', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('G', 'Granted'), ('P', 'Processing'), ('D', 'Denied'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
