# Generated by Django 5.2.8 on 2025-12-19 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('plan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlaunchrequest',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='users.profile'),
        ),
        migrations.AddField(
            model_name='eventlaunchrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='plan.plan'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at'], name='events_even_start_a_268ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant'], name='events_even_tenant__d9a6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='events_even_is_publ_cc4b67_idx'),
        ),
    ]
