# Generated by Django 5.2.8 on 2025-11-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventlaunchrequest'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlaunchrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='plan.plan'),
        ),
    ]
