# Generated by Django 5.2.8 on 2025-11-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventlaunchrequest_plan'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlaunchrequest',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='users.profile'),
        ),
    ]
