# Generated by Django 5.2.8 on 2025-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventlaunchrequest_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlaunchrequest',
            name='password',
            field=models.CharField(blank=True, help_text='This is the password you will use to login into your subdomain', max_length=128),
        ),
    ]
