# Generated by Django 5.2.8 on 2025-11-30 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLaunchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, help_text='This is the password you will use to login into your subdomain', max_length=128)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('concert', 'Concert / Festival'), ('conference', 'Conference / Expo'), ('training', 'Training / Workshop'), ('church', 'Church / Charity Event'), ('sports', 'Sports / Tournament'), ('other', 'Other')], max_length=50)),
                ('event_details', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('G', 'Granted'), ('P', 'Processing'), ('D', 'Denied'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.client')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
