# Generated by Django 5.2.8 on 2025-12-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
