# Generated by Django 5.2.8 on 2025-12-19 00:36

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, help_text='This will act as the subdomain. fidel in fidel.ticket.io', max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('domain', models.CharField(db_index=True, help_text=('This include the schema_name and the base domain. i.e fidel.ticket.io',), max_length=253, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
