# Generated by Django 5.2.8 on 2025-12-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User responsible for managing this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client'),
        ),
    ]
