# Generated by Django 5.2.8 on 2025-11-12 07:08

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(db_index=True, help_text='This will act as the subdomain. fidel in fidel.ticket.io', max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, help_text=('This include the schema_name and the base domain. i.e fidel.ticket.io',), max_length=253, unique=True),
        ),
    ]
