# Generated by Django 5.2.8 on 2025-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
