# Generated by Django 5.2.8 on 2025-11-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='event_id',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['start_at'], name='tickets_eve_start_a_6e6ea4_idx'), models.Index(fields=['is_published'], name='tickets_eve_is_publ_27db9a_idx')],
            },
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_ticket_type', to='tickets.event'),
        ),
    ]
