# Generated by Django 5.2.8 on 2025-11-30 03:39

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User responsible for managing this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(db_index=True, help_text='This will act as the subdomain. fidel in fidel.ticket.io', max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, help_text=('This include the schema_name and the base domain. i.e fidel.ticket.io',), max_length=253, unique=True),
        ),
    ]
