# Generated by Django 5.2.8 on 2025-12-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price_percentage', models.DecimalField(decimal_places=2, help_text='Percentage per ticket', max_digits=5)),
                ('card_color', models.CharField(blank=True, help_text='Bootstrap color for card header', max_length=100)),
                ('button_class', models.CharField(blank=True, help_text='Bootstrap button class', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plan.plan')),
            ],
        ),
    ]
