# Generated by Django 5.2.8 on 2025-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='button_class',
            field=models.CharField(blank=True, help_text='Bootstrap button class', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='card_color',
            field=models.CharField(blank=True, help_text='Bootstrap color for card header', max_length=100),
        ),
    ]
